foreground #ebdfe5
background #171216

selection_foreground #4c1f49
selection_background #f1b3e6

cursor #f1b3e6
cursor_text_color #4c1f49

url_color #f1b3e6

active_border_color #f1b3e6
inactive_border_color #9a8d95

# Normal colors

color0  #3a3338
color1  #ffb4ab
color2  #f5b8a7
color3  #dabfd2
color4  #f1b3e6
color5  #dabfd2
color6  #f5b8a7
color7  #ebdfe5

# Bright colors

color8  #9a8d95
color9  #ffb4ab
color10 #f5b8a7
color11 #dabfd2
color12 #f1b3e6
color13 #dabfd2
color14 #f5b8a7
color15 #ebdfe5
