[global]
    frame_color = "#acc7ff"
    separator_color = "#8e9099"

[urgency_low]
    background = "#1a1b20"
    foreground = "#e2e2e9"
    frame_color = "#acc7ff"

[urgency_normal]
    background = "#1e2025"
    foreground = "#e2e2e9"
    frame_color = "#acc7ff"

[urgency_critical]
    background = "#93000a"
    foreground = "#ffdad6"
    frame_color = "#ffb4ab"
