$background = #181216
$surface = #181216
$surface_container_highest = #3a3337
$on_surface = #ecdfe5
$on_surface_variant = #d2c2ca

$primary = #f4b2e2
$secondary = #dcbed1
$error = #ffb4ab

$surface_container_highestcc = #3a3337cc
$primaryff = #f4b2e2ff
$on_surfaceff = #ecdfe5ff
$on_surface_variantff = #d2c2caff
$errorff = #ffb4abff
