background {
    monitor =
    # Указываем путь к твоим обоям, hyprlock сам сделает красивый blur
    path = /home/sairex/Pictures/Wallpapers/9Tk0g7.jpg
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

# ЧАСЫ
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(205, 214, 244, 1.0)
    font_size = 75
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 150
    halign = center
    valign = center
}

# ПОЛЕ ВВОДА ПАРОЛЯ
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2 # Size of input-field dots
    dots_spacing = 0.15 # Scale of dots' absolute size
    dots_center = true
    outer_color = rgba(137, 180, 250, 1.0) # Синяя рамка (Catppuccin Blue)
    inner_color = rgba(30, 30, 46, 0.8)    # Темный фон с прозрачностью
    font_color = rgba(205, 214, 244, 1.0)
    fade_on_empty = false
    placeholder_text = <i>Введи пароль...</i>
    hide_input = false
    
    # Цвета состояний
    check_color = rgba(249, 226, 175, 1.0) # Желтый при проверке
    fail_color = rgba(243, 139, 168, 1.0)  # Красный при ошибке
    fail_text = <i>Неверный пароль! ($ATTEMPTS)</i>
    
    position = 0, -20
    halign = center
    valign = center
}
