$background = rgba({{colors.background.default.hex}}ff)
$surface = rgba({{colors.surface.default.hex}}f2)
$surface_container = rgba({{colors.surface_container.default.hex}}ff)

$on_surface = rgba({{colors.on_surface.default.hex}}ff)
$on_surface_variant = rgba({{colors.on_surface_variant.default.hex}}ff)

$primary = rgba({{colors.primary.default.hex}}ff)
$secondary = rgba({{colors.secondary.default.hex}}ff)

$error = rgba({{colors.error.default.hex}}ff)
